// <auto-generated>
//     Arquivo gerado automaticamente por ferramentas do .NET.
//     Este arquivo contém os acessores fortemente tipados para o arquivo Messages.resx.
// </auto-generated>

using System;
using System.Reflection;
using System.Resources;
using System.Globalization;

namespace Chronosystem.Application.Resources
{
    /// <summary>
    /// Classe estática que expõe acessores fortemente tipados para mensagens multilíngues.
    /// </summary>
    /// <remarks>
    /// As chaves são resolvidas dinamicamente a partir dos arquivos .resx localizados
    /// em <c>Chronosystem.Application.Resources</c>.
    /// </remarks>
    public static class Messages
    {
        private static readonly ResourceManager resourceManager =
            new ResourceManager("Chronosystem.Application.Resources.Messages", typeof(Messages).Assembly);

        public static string Get(string name) =>
            resourceManager.GetString(name, CultureInfo.CurrentUICulture) ?? $"[[{name}]]";

        // =====================================================================
        // 🌍 GLOBAL
        // =====================================================================
        public static string Validation_RequiredField => Get(nameof(Validation_RequiredField));
        public static string Validation_MinLength => Get(nameof(Validation_MinLength));
        public static string Validation_MaxLength => Get(nameof(Validation_MaxLength));
        public static string Validation_InvalidFormat => Get(nameof(Validation_InvalidFormat));
        public static string Validation_UserId_Required => Get(nameof(Validation_UserId_Required));
        public static string Validation_Id_Mismatch => Get(nameof(Validation_Id_Mismatch));
        public static string Validation_Request_Invalid => Get(nameof(Validation_Request_Invalid));

        // =====================================================================
        // 🏢 UNITS
        // =====================================================================
        public static string Unit_Id_Required => Get(nameof(Unit_Id_Required));
        public static string Unit_Name_Required => Get(nameof(Unit_Name_Required));
        public static string Unit_Name_MinLength => Get(nameof(Unit_Name_MinLength));
        public static string Unit_Name_MaxLength => Get(nameof(Unit_Name_MaxLength));
        public static string Unit_Name_AlreadyExists => Get(nameof(Unit_Name_AlreadyExists));
        public static string Unit_NotFound => Get(nameof(Unit_NotFound));
        public static string Unit_List_Empty => Get(nameof(Unit_List_Empty));

        // =====================================================================
        // 👩‍⚕️ PROFESSIONALS
        // =====================================================================
        public static string Professional_User_NotFound => Get(nameof(Professional_User_NotFound));
        public static string Professional_User_InvalidRole => Get(nameof(Professional_User_InvalidRole));
        public static string Professional_User_AlreadyLinked => Get(nameof(Professional_User_AlreadyLinked));
        public static string Professional_RegistryCode_AlreadyExists => Get(nameof(Professional_RegistryCode_AlreadyExists));
        public static string Professional_NotFound => Get(nameof(Professional_NotFound));
        public static string Professional_RegistryCode_MaxLength => Get(nameof(Professional_RegistryCode_MaxLength));
        public static string Professional_Specialty_MaxLength => Get(nameof(Professional_Specialty_MaxLength));

        // =====================================================================
        // 👤 USERS
        // =====================================================================
        public static string User_Email_AlreadyExists => Get(nameof(User_Email_AlreadyExists));
        public static string User_NotFound => Get(nameof(User_NotFound));
        public static string User_Password_Required => Get(nameof(User_Password_Required));
        public static string User_Email_Required => Get(nameof(User_Email_Required));
        public static string User_Email_Invalid => Get(nameof(User_Email_Invalid));
        public static string User_Inactive => Get(nameof(User_Inactive));
        public static string User_Password_Invalid => Get(nameof(User_Password_Invalid));
        public static string User_Role_Invalid => Get(nameof(User_Role_Invalid));

        // =====================================================================
        // 🏢 TENANTS
        // =====================================================================
        public static string Tenant_Subdomain_Invalid => Get(nameof(Tenant_Subdomain_Invalid));
        public static string Tenant_Subdomain_AlreadyExists => Get(nameof(Tenant_Subdomain_AlreadyExists));
        public static string Tenant_Header_Required => Get(nameof(Tenant_Header_Required));
        public static string Tenant_Header_InvalidFormat => Get(nameof(Tenant_Header_InvalidFormat));
        public static string Tenant_Header_MissingClaim => Get(nameof(Tenant_Header_MissingClaim));
        public static string Tenant_Header_Mismatch => Get(nameof(Tenant_Header_Mismatch));

        // =====================================================================
        // 🔐 AUTH
        // =====================================================================
        public static string Auth_SignUp_Success => Get(nameof(Auth_SignUp_Success));
        public static string Auth_Refresh_InvalidOrExpired => Get(nameof(Auth_Refresh_InvalidOrExpired));

        // ✅ Novas mensagens usadas no UserClaimsExtensions
        public static string Auth_InvalidToken_UserNotInContext => Get(nameof(Auth_InvalidToken_UserNotInContext));
        public static string Auth_InvalidToken_SubClaimMissingOrMalformed => Get(nameof(Auth_InvalidToken_SubClaimMissingOrMalformed));
    }
}
